const COPY = {
  "en": {
    "home": "Home",
    "about": "About Us",
    "vision": "Vision & Mission",
    "philosophy": "Our Philosophy",
    "products": "Products",
    "wellness": "Wellness Journal",
    "services": "Services",
    "quality": "Quality",
    "contact": "Contact",
    "browse": "Explore products",
    "discover": "Discover our approach",
    "more": "Read more",
    "view": "View concept",
    "concept": "CONCEPT · NOT FOR SALE",
    "note": "Product images are design concepts. Ingredients, claims, manufacturing origin and availability require confirmation before commercial use.",
    "hero": "Science and nature, thoughtfully connected.",
    "subhero": "A developing portfolio of nutritional and wellness concepts, guided by scientific thinking, careful sourcing and a commitment to transparent communication.",
    "featured": "Explore our product concepts",
    "featuredDesc": "Discover proposed nutritional, botanical and specialty formats. Product specifications remain subject to verification.",
    "values": "What guides our work",
    "valuesIntro": "Scientific thinking, transparent communication and responsible collaboration form the basis of our approach.",
    "aboutTitle": "About Pharmed UG",
    "aboutIntro": "Pharmed UG is a Germany-based business initiative focused on nutritional supplements, wellness products and international partnerships.",
    "aboutBody": "Our proposed activities include product sourcing, portfolio development, private-label cooperation and distribution. We aim to connect expertise in food science, biotechnology and quality assurance with qualified manufacturing and commercial partners, including opportunities between Europe, Egypt and other international markets.",
    "visionTitle": "Our vision, mission and aims",
    "visionIntro": "A clear direction for a developing business.",
    "visionH": "Vision",
    "visionP": "To become a trusted international partner for scientifically informed nutritional and wellness products, connecting research, responsible business and quality-focused collaboration.",
    "missionH": "Mission",
    "missionP": "To identify and develop thoughtful product concepts, evaluate ingredients and suppliers, and build long-term partnerships grounded in transparency and applicable quality requirements.",
    "aimH": "Our aims",
    "aimP": "Develop a focused product portfolio; seek qualified manufacturers and ingredient suppliers; explore private-label opportunities; and support responsible cross-border cooperation.",
    "philosophyTitle": "Our philosophy",
    "philosophyIntro": "We believe science and nature are complementary when product decisions are guided by evidence, safety and clarity.",
    "phil1H": "Science-led thinking",
    "phil1P": "We aim to examine ingredient identity, formulation rationale and supporting evidence instead of assuming that natural ingredients are automatically beneficial.",
    "phil2H": "Responsible quality",
    "phil2P": "We intend to work with suitable partners and consider specifications, traceability, labeling and applicable regulatory obligations early in development.",
    "phil3H": "Transparent communication",
    "phil3P": "We distinguish design concepts from available products and avoid presenting unverified health claims or manufacturing statements as established facts.",
    "productsTitle": "Product concepts",
    "productsIntro": "Browse our proposed portfolio by category. Each page describes the concept and shows its current design illustration.",
    "search": "Search products…",
    "all": "All",
    "botanical": "Botanical & wellness",
    "nutrition": "Nutrition",
    "functional": "Functional formats",
    "special": "Specialty",
    "back": "Back to products",
    "related": "Explore more concepts",
    "wellnessTitle": "Wellness journal",
    "wellnessIntro": "Practical, general guidance to complement balanced living. Supplements are not substitutes for a varied diet or medical care.",
    "well1H": "Build a balanced plate",
    "well1P": "Aim for variety across vegetables, fruit, whole grains and suitable protein sources. Hydration and appropriate portions matter more than any single ingredient.",
    "well2H": "Make movement routine",
    "well2P": "Choose enjoyable physical activity and build consistency gradually. Adapt intensity and duration to your circumstances.",
    "well3H": "Protect your sleep",
    "well3P": "Keep a regular sleep schedule and make time for rest. If persistent sleep problems occur, consult a qualified professional.",
    "well4H": "Use supplements responsibly",
    "well4P": "Check the ingredient list, dosage, allergies and potential interactions with medicines. Seek professional advice when needed.",
    "servicesTitle": "Services and partnerships",
    "servicesIntro": "Our proposed commercial activities are being developed with a focus on suitable partners and clear responsibilities.",
    "s1H": "Ingredient and product sourcing",
    "s1P": "Exploring qualified ingredient suppliers and manufacturers, with attention to specifications and traceability.",
    "s2H": "Private-label cooperation",
    "s2P": "Developing opportunities for collaborative packaging and product concepts with appropriate manufacturing partners.",
    "s3H": "International partnerships",
    "s3P": "Exploring commercial links between Germany, Europe, Egypt and wider international markets, subject to applicable trade and regulatory requirements.",
    "qualityTitle": "Our quality approach",
    "qualityIntro": "Quality is a process, not an unsupported label.",
    "qualityBody": "Our intended approach includes documented specifications, supplier assessment, traceability, appropriate labeling and regulatory review. Product-specific certificates, test results and manufacturing claims will be presented only when verified.",
    "contactTitle": "Contact Pharmed UG",
    "contactIntro": "For product concepts, sourcing or partnership enquiries.",
    "contactPending": "Company email, registered address and official contact details will be added after confirmation.",
    "legalPending": "Draft legal page. Complete and legally review before commercial publication.",
    "impressum": "Legal notice (Impressum)",
    "privacy": "Privacy policy",
    "legal": "Legal",
    "updated": "Website draft · product concepts only",
    "noResults": "No matching products found."
  },
  "de": {
    "home": "Startseite",
    "about": "Über uns",
    "vision": "Vision & Mission",
    "philosophy": "Philosophie",
    "products": "Produkte",
    "wellness": "Wohlbefinden",
    "services": "Leistungen",
    "quality": "Qualität",
    "contact": "Kontakt",
    "browse": "Produkte entdecken",
    "discover": "Unseren Ansatz kennenlernen",
    "more": "Mehr erfahren",
    "view": "Konzept ansehen",
    "concept": "KONZEPT · NICHT IM VERKAUF",
    "note": "Produktbilder sind Gestaltungskonzepte. Zutaten, Aussagen, Herstellungsland und Verfügbarkeit müssen vor der kommerziellen Nutzung bestätigt werden.",
    "hero": "Wissenschaft und Natur – bewusst verbunden.",
    "subhero": "Ein entstehendes Portfolio für Nahrungsergänzung und Wohlbefinden, geprägt von wissenschaftlichem Denken, sorgfältiger Beschaffung und transparenter Kommunikation.",
    "featured": "Unsere Produktkonzepte",
    "featuredDesc": "Entdecken Sie geplante Nährstoff-, Pflanzen- und Spezialprodukte. Die Produktspezifikationen müssen noch überprüft werden.",
    "values": "Was uns leitet",
    "valuesIntro": "Wissenschaftliches Denken, transparente Kommunikation und verantwortungsvolle Zusammenarbeit prägen unseren Ansatz.",
    "aboutTitle": "Über Pharmed UG",
    "aboutIntro": "Pharmed UG ist eine in Deutschland geplante Geschäftsinitiative für Nahrungsergänzungsmittel, Wellnessprodukte und internationale Partnerschaften.",
    "aboutBody": "Zu den vorgesehenen Tätigkeiten zählen Produktbeschaffung, Portfolioentwicklung, Private-Label-Kooperationen und Vertrieb. Wir möchten Fachwissen aus Lebensmittelwissenschaft, Biotechnologie und Qualitätssicherung mit geeigneten Herstellungs- und Handelspartnern verbinden, auch zwischen Europa, Ägypten und weiteren internationalen Märkten.",
    "visionTitle": "Unsere Vision, Mission und Ziele",
    "visionIntro": "Eine klare Ausrichtung für ein Unternehmen im Aufbau.",
    "visionH": "Vision",
    "visionP": "Ein vertrauenswürdiger internationaler Partner für wissenschaftlich fundierte Ernährungs- und Wellnessprodukte zu werden und Forschung, verantwortungsvolles Handeln und qualitätsorientierte Zusammenarbeit zu verbinden.",
    "missionH": "Mission",
    "missionP": "Durchdachte Produktkonzepte zu identifizieren und zu entwickeln, Zutaten und Lieferanten zu bewerten und langfristige Partnerschaften auf Basis von Transparenz und geltenden Qualitätsanforderungen aufzubauen.",
    "aimH": "Unsere Ziele",
    "aimP": "Ein fokussiertes Produktportfolio entwickeln, qualifizierte Hersteller und Rohstofflieferanten finden, Private-Label-Möglichkeiten prüfen und verantwortungsvolle internationale Zusammenarbeit fördern.",
    "philosophyTitle": "Unsere Philosophie",
    "philosophyIntro": "Wissenschaft und Natur ergänzen sich, wenn Produktentscheidungen auf Evidenz, Sicherheit und Klarheit beruhen.",
    "phil1H": "Wissenschaftlicher Ansatz",
    "phil1P": "Wir möchten Identität, Rezeptur und Evidenz von Inhaltsstoffen prüfen, statt natürliche Herkunft mit nachgewiesenem Nutzen gleichzusetzen.",
    "phil2H": "Verantwortungsvolle Qualität",
    "phil2P": "Wir streben die Zusammenarbeit mit geeigneten Partnern an und berücksichtigen Spezifikationen, Rückverfolgbarkeit, Kennzeichnung und regulatorische Pflichten frühzeitig.",
    "phil3H": "Transparente Kommunikation",
    "phil3P": "Wir unterscheiden Konzepte von verfügbaren Produkten und stellen unbestätigte Gesundheits- oder Herkunftsangaben nicht als gesicherte Tatsachen dar.",
    "productsTitle": "Produktkonzepte",
    "productsIntro": "Durchsuchen Sie unser geplantes Portfolio nach Kategorien. Jede Produktseite beschreibt das Konzept und zeigt das aktuelle Design.",
    "search": "Produkte suchen…",
    "all": "Alle",
    "botanical": "Pflanzlich & Wellness",
    "nutrition": "Ernährung",
    "functional": "Funktionelle Formate",
    "special": "Spezialprodukte",
    "back": "Zurück zu den Produkten",
    "related": "Weitere Konzepte entdecken",
    "wellnessTitle": "Wissenswertes zum Wohlbefinden",
    "wellnessIntro": "Allgemeine Hinweise für einen ausgewogenen Lebensstil. Nahrungsergänzungsmittel ersetzen weder eine abwechslungsreiche Ernährung noch medizinische Betreuung.",
    "well1H": "Ausgewogen essen",
    "well1P": "Achten Sie auf Vielfalt bei Gemüse, Obst, Vollkornprodukten und geeigneten Eiweißquellen. Ausreichendes Trinken und angemessene Portionen sind wichtig.",
    "well2H": "Bewegung in den Alltag bringen",
    "well2P": "Wählen Sie eine Aktivität, die Ihnen Freude macht, und steigern Sie die Regelmäßigkeit schrittweise.",
    "well3H": "Schlaf schützen",
    "well3P": "Pflegen Sie regelmäßige Schlafzeiten und planen Sie Erholung ein. Bei anhaltenden Problemen hilft qualifizierter Rat.",
    "well4H": "Nahrungsergänzung bewusst nutzen",
    "well4P": "Prüfen Sie Zutaten, Dosierung, Allergene und mögliche Wechselwirkungen mit Medikamenten. Holen Sie bei Bedarf fachlichen Rat ein.",
    "servicesTitle": "Leistungen & Partnerschaften",
    "servicesIntro": "Unsere geplanten Geschäftsaktivitäten werden mit Blick auf geeignete Partner und klare Verantwortlichkeiten entwickelt.",
    "s1H": "Rohstoff- und Produktbeschaffung",
    "s1P": "Suche nach geeigneten Rohstofflieferanten und Herstellern unter Berücksichtigung von Spezifikationen und Rückverfolgbarkeit.",
    "s2H": "Private-Label-Kooperation",
    "s2P": "Entwicklung von Verpackungs- und Produktkonzepten gemeinsam mit geeigneten Herstellungspartnern.",
    "s3H": "Internationale Partnerschaften",
    "s3P": "Prüfung von Handelsbeziehungen zwischen Deutschland, Europa, Ägypten und weiteren Märkten unter Beachtung geltender Anforderungen.",
    "qualityTitle": "Unser Qualitätsansatz",
    "qualityIntro": "Qualität ist ein Prozess, kein unbelegtes Versprechen.",
    "qualityBody": "Unser geplanter Ansatz umfasst dokumentierte Spezifikationen, Lieferantenbewertung, Rückverfolgbarkeit, geeignete Kennzeichnung und regulatorische Prüfung. Produktspezifische Zertifikate, Prüfergebnisse und Herkunftsangaben werden nur nach Verifizierung veröffentlicht.",
    "contactTitle": "Kontakt zu Pharmed UG",
    "contactIntro": "Für Anfragen zu Produktkonzepten, Beschaffung oder Partnerschaften.",
    "contactPending": "Firmen-E-Mail, eingetragene Anschrift und offizielle Kontaktdaten werden nach Bestätigung ergänzt.",
    "legalPending": "Entwurf der Rechtstexte. Vor kommerzieller Veröffentlichung vervollständigen und rechtlich prüfen.",
    "impressum": "Impressum",
    "privacy": "Datenschutzerklärung",
    "legal": "Rechtliches",
    "updated": "Website-Entwurf · ausschließlich Produktkonzepte",
    "noResults": "Keine passenden Produkte gefunden."
  },
  "ar": {
    "home": "الرئيسية",
    "about": "من نحن",
    "vision": "الرؤية والرسالة",
    "philosophy": "فلسفتنا",
    "products": "المنتجات",
    "wellness": "نصائح العافية",
    "services": "خدماتنا",
    "quality": "الجودة",
    "contact": "اتصل بنا",
    "browse": "استكشف المنتجات",
    "discover": "تعرف على نهجنا",
    "more": "اقرأ المزيد",
    "view": "عرض التصور",
    "concept": "تصميم أولي · غير معروض للبيع",
    "note": "صور المنتجات تصاميم أولية. يجب تأكيد المكونات والادعاءات وبلد التصنيع والتوافر قبل الاستخدام التجاري.",
    "hero": "العلم والطبيعة في تناغم مدروس.",
    "subhero": "مجموعة قيد التطوير من مفاهيم المكملات الغذائية ومنتجات العافية، تستند إلى التفكير العلمي والتوريد المدروس والتواصل الشفاف.",
    "featured": "استكشف مفاهيم منتجاتنا",
    "featuredDesc": "تعرف على منتجات التغذية والمكونات النباتية والمنتجات المتخصصة المقترحة. المواصفات النهائية قيد التحقق.",
    "values": "مبادئنا",
    "valuesIntro": "التفكير العلمي والتواصل الشفاف والتعاون المسؤول هي أساس نهجنا.",
    "aboutTitle": "من نحن – Pharmed UG",
    "aboutIntro": "Pharmed UG مشروع تجاري مقره ألمانيا يركز على المكملات الغذائية ومنتجات العافية والشراكات الدولية.",
    "aboutBody": "تشمل الأنشطة المقترحة توريد المنتجات وتطوير مجموعة المنتجات والتعاون في العلامات التجارية الخاصة والتوزيع. نهدف إلى ربط الخبرات في علوم الأغذية والتقنية الحيوية وضمان الجودة بشركاء تصنيع وتجارة مؤهلين، بما في ذلك فرص التعاون بين أوروبا ومصر والأسواق الدولية الأخرى.",
    "visionTitle": "رؤيتنا ورسالتنا وأهدافنا",
    "visionIntro": "اتجاه واضح لمشروع تجاري في مرحلة التطوير.",
    "visionH": "الرؤية",
    "visionP": "أن نصبح شريكاً دولياً موثوقاً في المنتجات الغذائية ومنتجات العافية القائمة على المعرفة العلمية، وأن نربط البحث العلمي بالأعمال المسؤولة والتعاون الموجه نحو الجودة.",
    "missionH": "الرسالة",
    "missionP": "تحديد وتطوير مفاهيم منتجات مدروسة، وتقييم المكونات والموردين، وبناء شراكات طويلة الأمد على أساس الشفافية ومتطلبات الجودة المعمول بها.",
    "aimH": "الأهداف",
    "aimP": "تطوير مجموعة منتجات مركزة، والبحث عن مصنعين وموردي مكونات مؤهلين، واستكشاف فرص العلامة التجارية الخاصة، ودعم التعاون التجاري الدولي المسؤول.",
    "philosophyTitle": "فلسفتنا",
    "philosophyIntro": "نؤمن بأن العلم والطبيعة يكمل أحدهما الآخر عندما تستند قرارات المنتجات إلى الأدلة والسلامة والوضوح.",
    "phil1H": "تفكير يستند إلى العلم",
    "phil1P": "نسعى إلى فحص هوية المكونات ومنطق التركيبات والأدلة الداعمة، دون افتراض أن المكونات الطبيعية مفيدة تلقائياً.",
    "phil2H": "جودة مسؤولة",
    "phil2P": "نطمح إلى التعاون مع شركاء مناسبين ومراعاة المواصفات وإمكانية التتبع والملصقات والمتطلبات التنظيمية منذ مراحل التطوير الأولى.",
    "phil3H": "تواصل شفاف",
    "phil3P": "نميز بين التصاميم الأولية والمنتجات المتاحة، ولا نقدم الادعاءات الصحية أو معلومات التصنيع غير المؤكدة بوصفها حقائق ثابتة.",
    "productsTitle": "مفاهيم المنتجات",
    "productsIntro": "تصفح مجموعة منتجاتنا المقترحة حسب الفئة. تتضمن كل صفحة وصفاً للمفهوم وصورة التصميم الحالي.",
    "search": "ابحث عن منتج…",
    "all": "الكل",
    "botanical": "نباتات وعافية",
    "nutrition": "التغذية",
    "functional": "أشكال مبتكرة",
    "special": "منتجات متخصصة",
    "back": "العودة إلى المنتجات",
    "related": "اكتشف مفاهيم أخرى",
    "wellnessTitle": "دليل العافية",
    "wellnessIntro": "إرشادات عامة لنمط حياة متوازن. لا تحل المكملات الغذائية محل النظام الغذائي المتنوع أو الرعاية الطبية.",
    "well1H": "غذاء متوازن",
    "well1P": "نوّع بين الخضروات والفواكه والحبوب الكاملة ومصادر البروتين المناسبة. الترطيب والكميات المناسبة مهمان.",
    "well2H": "اجعل الحركة عادة",
    "well2P": "اختر نشاطاً بدنياً تستمتع به، وزد الانتظام تدريجياً بما يلائم ظروفك.",
    "well3H": "اعتنِ بنومك",
    "well3P": "حافظ على أوقات نوم منتظمة وخصص وقتاً للراحة. استشر مختصاً عند استمرار المشكلات.",
    "well4H": "استخدم المكملات بمسؤولية",
    "well4P": "تحقق من المكونات والجرعات والحساسية والتداخلات المحتملة مع الأدوية، واستشر مختصاً عند الحاجة.",
    "servicesTitle": "الخدمات والشراكات",
    "servicesIntro": "نعمل على تطوير أنشطتنا التجارية المقترحة مع التركيز على الشركاء المناسبين وتحديد المسؤوليات.",
    "s1H": "توريد المكونات والمنتجات",
    "s1P": "استكشاف موردي المكونات والمصنعين المؤهلين مع مراعاة المواصفات وإمكانية التتبع.",
    "s2H": "التعاون في العلامات التجارية الخاصة",
    "s2P": "تطوير فرص تصميم العبوات ومفاهيم المنتجات بالتعاون مع شركاء تصنيع مناسبين.",
    "s3H": "شراكات دولية",
    "s3P": "استكشاف الروابط التجارية بين ألمانيا وأوروبا ومصر والأسواق الدولية الأخرى وفق المتطلبات المعمول بها.",
    "qualityTitle": "نهجنا في الجودة",
    "qualityIntro": "الجودة عملية مستمرة وليست مجرد شعار.",
    "qualityBody": "يشمل نهجنا المقترح المواصفات الموثقة وتقييم الموردين وإمكانية التتبع ووضع الملصقات المناسبة والمراجعة التنظيمية. لن ننشر شهادات أو نتائج اختبارات أو ادعاءات تصنيع خاصة بالمنتجات إلا بعد التحقق منها.",
    "contactTitle": "اتصل بـ Pharmed UG",
    "contactIntro": "للاستفسارات بشأن مفاهيم المنتجات والتوريد والشراكات.",
    "contactPending": "ستضاف معلومات البريد الإلكتروني للشركة والعنوان المسجل وبيانات الاتصال الرسمية بعد تأكيدها.",
    "legalPending": "مسودة صفحة قانونية. يجب استكمالها ومراجعتها قانونياً قبل النشر التجاري.",
    "impressum": "البيانات القانونية",
    "privacy": "سياسة الخصوصية",
    "legal": "المعلومات القانونية",
    "updated": "نسخة تجريبية للموقع · تصاميم منتجات فقط",
    "noResults": "لم يتم العثور على منتجات مطابقة."
  }
};
