/* Pharmed UG Scientific Wellness Academy (2026). Educational, not medical advice.
 * Added after app.js and pharmed-enhancements.js. No cookies, trackers, network calls,
 * AI diagnosis or claims that concepts have been clinically tested.
 */
(()=>{'use strict';
const asset='assets/mascots/';
const pubmed=q=>'https://pubmed.ncbi.nlm.nih.gov/?term='+encodeURIComponent(q);
const source={
 integrative:'https://www.nccih.nih.gov/health/are-you-considering-a-complementary-health-approach',
 omega:'https://ods.od.nih.gov/factsheets/Omega3FattyAcids-HealthProfessional/',
 tcm:'https://www.nccih.nih.gov/health/traditional-chinese-medicine-what-you-need-to-know',
 ginger:'https://www.nccih.nih.gov/health/ginger/',
 ginseng:'https://www.nccih.nih.gov/health/asian-ginseng',
 milkthistle:'https://www.nccih.nih.gov/health/milk-thistle',
 ginkgo:'https://www.nccih.nih.gov/health/ginkgo',
 turmeric:'https://www.nccih.nih.gov/health/turmeric',
 herbs:'https://www.nccih.nih.gov/health/providers/digest/herb-drug-interactions-science',
 probio:'https://pubmed.ncbi.nlm.nih.gov/33574872/',
 vitamins:'https://ods.od.nih.gov/factsheets/list-all/',
 eu:'https://food.ec.europa.eu/food-safety/labelling-and-nutrition/nutrition-and-health-claims_en',
 european:'https://www.ema.europa.eu/en/human-regulatory-overview/herbal-medicinal-products/european-union-herbal-monographs'
};
const terms={
 en:{relatedConcepts:'Associated Pharmed concepts (not medical claims)',integrativeTitle:'Complementary, alternative & integrative health',complementaryLabel:'Complementary',complementaryNote:'Used alongside evidence-based conventional medical care.',alternativeLabel:'Alternative',alternativeNote:'Used instead of conventional medical care; unproven approaches should not replace effective treatment.',integrativeLabel:'Integrative',integrativeNote:'Coordinates conventional care with evaluated complementary options and shared medical decisions.',science:'Science & research',academy:'Pharmed Science Academy',intro:'Meet the Pharmed UG characters and explore evidence-aware nutrition, botanical research, traditional Chinese medicine, and product formulation. Information is educational, not treatment advice.',characters:'Scientific guides for each character',learn:'Explore scientific facts',facts:'Research overview',caution:'Evidence & safety',read:'Read source',pubmed:'Explore studies on PubMed',brochure:'Historical brochure data, NOT verified current formula',recipe:'Ingredient profile / concept formulation',target:'Scientific area of interest',risk:'Important quality or safety notes',dossier:'Product science & formulation',specifics:'Historical quantities',concept:'Concept only: quantities and final composition not established',sourceinfo:'Information is not proof of product efficacy, authorisation or availability.',citation:'External scientific reference',details:'View product science',safety:'Safety matters',claims:'Claims require authorisation',evidence:'How evidence works',search:'Search science topics…',all:'All fields',nutrition:'Nutrition',herbal:'Herbal research',tcm:'Chinese herbal medicine',quality:'Quality & safety',research:'Research methods',gallery:'Return to mascot gallery',home:'Discover the Academy',three:'Explore product dossiers',sourcewarning:'The attached brochure is historical; verify ingredient amounts, allergens, suitability and authorised claims before any commercial use.',ingredient:'Listed ingredient or characteristic',pergum:'Per gum, historical',per3:'Three gums, historical',per2:'Two gums, historical',perstraw:'One straw, historical',form:'Preparation format',notdose:'No dosage or medicinal prescription is supplied here.',sourceNote:'Topics and links support general education. Evidence for an ingredient or strain does not establish efficacy of a particular Pharmed concept.'},
 de:{relatedConcepts:'Zugeordnete Pharmed-Konzepte (keine Heilaussagen)',integrativeTitle:'Komplementäre, alternative und integrative Verfahren',complementaryLabel:'Komplementär',complementaryNote:'Zusätzlich zur wissenschaftlich etablierten medizinischen Versorgung.',alternativeLabel:'Alternativ',alternativeNote:'Anstelle etablierter Medizin; unbelegte Verfahren dürfen wirksame Behandlungen nicht ersetzen.',integrativeLabel:'Integrativ',integrativeNote:'Koordiniert Standardversorgung und bewertete ergänzende Ansätze in ärztlicher Abstimmung.',science:'Wissenschaft & Forschung',academy:'Pharmed Wissenschaftsakademie',intro:'Lernen Sie die Pharmed-Charaktere kennen und entdecken Sie evidenzorientierte Ernährung, Pflanzenforschung, traditionelle chinesische Medizin und Produktkonzepte. Dies sind Bildungsinformationen, keine Therapieempfehlungen.',characters:'Wissenschaftliche Themen der Figuren',learn:'Wissenschaftliche Informationen',facts:'Forschungsüberblick',caution:'Evidenz & Sicherheit',read:'Quelle öffnen',pubmed:'Studien bei PubMed',brochure:'Historische Broschürenangaben, keine bestätigte aktuelle Rezeptur',recipe:'Inhaltsstoffprofil / Konzeptrezeptur',target:'Wissenschaftlicher Themenbereich',risk:'Qualitäts- und Sicherheitsaspekte',dossier:'Produktwissenschaft & Rezeptur',specifics:'Historische Mengenangaben',concept:'Nur Konzept: finale Rezeptur und Mengen unbestätigt',sourceinfo:'Dies belegt weder die Wirksamkeit noch Zulassung oder Verfügbarkeit des Produkts.',citation:'Externe wissenschaftliche Quelle',details:'Produktwissenschaft anzeigen',safety:'Sicherheit beachten',claims:'Werbeaussagen brauchen Zulässigkeitsprüfung',evidence:'Evidenz einordnen',search:'Wissenschaftsthemen durchsuchen…',all:'Alle Themen',nutrition:'Ernährung',herbal:'Pflanzenforschung',tcm:'Chinesische Kräutermedizin',quality:'Qualität & Sicherheit',research:'Forschungsmethoden',gallery:'Zur Maskottchengalerie',home:'Akademie entdecken',three:'Produktdossiers entdecken',sourcewarning:'Diese Broschüre ist historisch. Zusammensetzung, Allergene, Eignung und zulässige Angaben vor Vermarktung prüfen.',ingredient:'Zutat bzw. Merkmal',pergum:'Pro Kaugummi, historisch',per3:'Drei Kaugummis, historisch',per2:'Zwei Kaugummis, historisch',perstraw:'Pro Trinkhalm, historisch',form:'Darreichungsform',notdose:'Hier wird keine medizinische Rezeptur oder Dosierungsempfehlung angegeben.',sourceNote:'Die Quellen dienen der allgemeinen Bildung. Evidenz zu einem Stoff oder Stamm beweist keine Wirksamkeit eines Pharmed-Konzepts.'},
 ar:{relatedConcepts:'مفاهيم فارمد المرتبطة (ليست ادعاءات علاجية)',integrativeTitle:'الطب التكميلي والبديل والتكاملي',complementaryLabel:'التكميلي',complementaryNote:'يُستخدم إلى جانب الرعاية الطبية التقليدية المبنية على الأدلة.',alternativeLabel:'البديل',alternativeNote:'يُستخدم بديلاً عن الرعاية الطبية المثبتة؛ لا ينبغي أن تحل الطرق غير المثبتة محل العلاج الفعال.',integrativeLabel:'التكاملي',integrativeNote:'ينسق العلاج المعتاد مع الأساليب التكميلية المقيّمة ضمن قرار طبي مشترك.',science:'العلم والبحوث',academy:'أكاديمية فارمد العلمية',intro:'تعرّف على شخصيات فارمد واستكشف التغذية المبنية على الأدلة وبحوث النباتات والطب الصيني التقليدي وتركيبات المنتجات. هذه معلومات تعليمية وليست توصيات علاجية.',characters:'المواضيع العلمية لكل شخصية',learn:'استكشف المعلومات العلمية',facts:'ملخص الأبحاث',caution:'الأدلة والسلامة',read:'قراءة المصدر',pubmed:'دراسات عبر PubMed',brochure:'بيانات كتيبات تاريخية وليست تركيبة حالية موثقة',recipe:'مكونات وتركيبة المفهوم',target:'مجال الاهتمام العلمي',risk:'ملاحظات الجودة والسلامة',dossier:'الملف العلمي وتركيبة المنتج',specifics:'الكميات التاريخية',concept:'فكرة أولية: الكميات والتركيبة النهائية غير مؤكدة',sourceinfo:'لا تثبت هذه المعلومات فعالية المنتج أو ترخيصه أو توافره.',citation:'مرجع علمي خارجي',details:'افتح معلومات المنتج العلمية',safety:'السلامة مهمة',claims:'الادعاءات الصحية تتطلب مراجعة تنظيمية',evidence:'كيف نقيم الأدلة',search:'ابحث في المواضيع العلمية…',all:'كل المجالات',nutrition:'التغذية',herbal:'بحوث الأعشاب',tcm:'طب الأعشاب الصيني',quality:'الجودة والسلامة',research:'منهجية البحث',gallery:'العودة إلى الشخصيات',home:'اكتشف الأكاديمية',three:'ملفات المنتجات العلمية',sourcewarning:'الكتيبات تاريخية؛ يجب التحقق من التراكيز والحساسية والملاءمة والادعاءات قبل أي تسويق.',ingredient:'المكون أو الخاصية',pergum:'لكل علكة، تاريخياً',per3:'لثلاث علكات، تاريخياً',per2:'لعلكتين، تاريخياً',perstraw:'لكل شفاطة، تاريخياً',form:'طريقة العرض',notdose:'لا يقدم الموقع جرعة علاجية أو وصفة دوائية.',sourceNote:'المراجع لأغراض تعليمية؛ ولا تثبت الدراسات المتعلقة بمكون أو سلالة فعالية منتج محدد من فارمد.'}
};
/* All 17 mascots are individually mapped to their science and one verified reference.
 * Different characters highlight the strength and limits of evidence, never guarantee an outcome.
 */
const subjects=[
 {id:'owl',cat:'research',name:['Research Owl','Forschungs-Eule','بومة البحث العلمي'],fact:['A randomized controlled trial compares an intervention with a control. Human efficacy claims require more than a laboratory mechanism.','Randomisierte Studien vergleichen eine Intervention mit einer Kontrolle. Laborbefunde allein reichen nicht als Wirksamkeitsnachweis beim Menschen.','تقارن التجارب العشوائية تدخلاً مع مجموعة ضابطة. ولا تكفي النتائج المخبرية وحدها لإثبات الفعالية لدى البشر.'],warn:['Study design, bias and effect size matter.','Studiendesign, Verzerrungen und Effektgröße sind entscheidend.','تصميم الدراسة والتحيز وحجم التأثير أمور حاسمة.'],url:source.eu,query:'randomized clinical trial herbal medicine evidence systematic review'},
 {id:'fox',cat:'herbal',name:['Botanical Fox','Botanischer Fuchs','الثعلب النباتي'],fact:['Botanical research begins with the correct Latin species, plant part and chemical fingerprint; a popular plant name is not a product specification.','Botanische Forschung benötigt Artname, Pflanzenteil und chemischen Fingerabdruck. Ein Trivialname ist keine Produktspezifikation.','تبدأ البحوث النباتية بتحديد النوع اللاتيني والجزء النباتي والبصمة الكيميائية؛ فالاسم الشائع ليس مواصفة للمنتج.'],warn:['Extracts vary by solvent, processing and batch.','Extrakte unterscheiden sich je nach Lösungsmittel, Verarbeitung und Charge.','تختلف المستخلصات بحسب المذيب والتصنيع والدفعة.'],url:source.european,query:'herbal medicine botanical identification standardization HPLC'},
 {id:'rabbit',cat:'nutrition',name:['Microbiome Rabbit','Mikrobiom-Kaninchen','أرنب الميكروبيوم'],fact:['Microbiome findings depend on bacterial strain, viable dose and target population; effects cannot be generalized from one probiotic to another.','Mikrobiomeffekte hängen von Bakterienstamm, lebensfähiger Dosis und Zielgruppe ab. Studien lassen sich nicht pauschal übertragen.','تعتمد نتائج الميكروبيوم على السلالة والجرعة الحية والفئة المدروسة، ولا يمكن تعميم أثر سلالة على أخرى.'],warn:['A strain study is not a trial of the proposed gum.','Eine Stammstudie ist kein Wirksamkeitsnachweis für den geplanten Kaugummi.','دراسة السلالة ليست دراسة سريرية للعلكة المقترحة.'],url:source.probio,query:'Lactobacillus salivarius SGL03 oral periodontal randomized trial'},
 {id:'bee',cat:'herbal',name:['Herbal Bee','Kräuter-Biene','نحلة الأعشاب'],fact:['Honey and botanical compounds can be investigated chemically, but laboratory antimicrobial findings do not prove that a consumer supplement treats infection.','Honig und Pflanzenstoffe können chemisch untersucht werden. Antimikrobielle Laborbefunde belegen aber keine Infektionsbehandlung durch ein Nahrungsergänzungsmittel.','يمكن دراسة العسل ومركبات النباتات مخبرياً، لكن التأثير المضاد للميكروبات في المختبر لا يثبت علاج العدوى بمكمل غذائي.'],warn:['Honey is not suitable for infants under one year.','Honig ist für Kinder unter einem Jahr ungeeignet.','لا يُعطى العسل للرضع دون عمر سنة.'],url:'https://www.cdc.gov/infant-botulism/about/index.html',query:'honey botanical polyphenols antimicrobial in vitro clinical evidence'},
 {id:'otter',cat:'nutrition',name:['Omega Otter','Omega-Otter','قضاعة أوميغا'],fact:['EPA and DHA are long-chain omega-3 fatty acids. Their clinical effects depend on intake, population and outcome.','EPA und DHA sind langkettige Omega-3-Fettsäuren. Klinische Effekte hängen von Zufuhr, Zielgruppe und Endpunkt ab.','يُعد EPA وDHA من أحماض أوميغا-3 طويلة السلسلة؛ وتعتمد النتائج السريرية على الجرعة والفئة والنتيجة المقاسة.'],warn:['Check fish/soy allergens in the historical gum concept.','Bei dem historischen Kaugummikonzept Fisch- und Sojaallergene prüfen.','يجب التحقق من مسببات الحساسية كالسمك والصويا في مفهوم العلكة التاريخي.'],url:source.omega,query:'EPA DHA omega 3 cardiovascular prevention meta analysis randomized trials'},
 {id:'robot',cat:'quality',name:['Probiotic Quality Robot','Qualitäts-Roboter','روبوت جودة البروبيوتيك'],fact:['For a live-culture product, verify strain identity, viable cell count at the end of shelf life and manufacturing stability.','Für Produkte mit lebenden Kulturen müssen Stammidentität, Lebendkeimzahl zum Haltbarkeitsende und Stabilität geprüft werden.','تستلزم المنتجات المحتوية على كائنات حية التحقق من هوية السلالة وعدد الخلايا الحية بنهاية الصلاحية والثبات الصناعي.'],warn:['Milligrams of a culture are not interchangeable with CFU.','Milligramm Kultur sind nicht gleichbedeutend mit KBE.','مليغرامات المستحضر البكتيري لا تعادل عدد الوحدات المكونة للمستعمرات.'],url:source.probio,query:'probiotic strain identity viability CFU shelf life stability'},
 {id:'leaf-spirit',cat:'tcm',name:['Traditional Wisdom Spirit','Traditions-Geist','روح الحكمة التقليدية'],fact:['Traditional Chinese herbal medicine is a complex medical tradition. Its historical use is not proof of therapeutic benefit under modern clinical standards.','Die chinesische Kräutermedizin ist eine komplexe Tradition. Historische Anwendung ersetzt keine moderne klinische Evidenz.','طب الأعشاب الصيني تقليد طبي معقد، ولا يُعد الاستخدام التاريخي دليلاً على الفعالية وفق معايير التجارب الحديثة.'],warn:['Botanical misidentification, contamination and drug interactions require careful attention.','Artverwechslung, Verunreinigungen und Wechselwirkungen erfordern sorgfältige Prüfung.','يجب الانتباه لتحديد النوع والتلوث والتداخلات الدوائية.'],url:source.tcm,query:'traditional Chinese herbal medicine systematic review quality safety'},
 {id:'koala',cat:'herbal',name:['Milk Thistle Koala','Mariendistel-Koala','كوالا شوك الحليب'],fact:['Milk thistle contains the silymarin group of compounds. Clinical trials for liver disease have produced inconsistent or limited results.','Mariendistel enthält Silymarin-Verbindungen. Klinische Leberstudien liefern widersprüchliche oder begrenzte Ergebnisse.','يحتوي شوك الحليب على مركبات السيليمارين، وتبقى النتائج السريرية لأمراض الكبد متضاربة أو محدودة.'],warn:['Avoid claims that milk thistle cures or detoxifies the liver.','Keine unbewiesenen Heilungs- oder „Leberentgiftungs“-Versprechen.','يجب تجنب ادعاءات شفاء الكبد أو إزالة السموم دون دليل.'],url:source.milkthistle,query:'Silybum marianum silymarin fatty liver randomized clinical trial'},
 {id:'chameleon',cat:'herbal',name:['Curcumin Chameleon','Kurkuma-Chamäleon','حرباء الكركمين'],fact:['Turmeric contains curcuminoids. Findings from cells and animals do not establish human prevention or treatment effects.','Kurkuma enthält Curcuminoide. Zell- und Tierbefunde belegen keine Prävention oder Therapie beim Menschen.','يحتوي الكركم على الكركمينويدات، ولا تثبت التجارب الخلوية والحيوانية الوقاية أو العلاج لدى البشر.'],warn:['Some high-bioavailability curcumin supplements have been associated with liver injury.','Einige Curcumin-Präparate mit erhöhter Bioverfügbarkeit wurden mit Leberschäden in Verbindung gebracht.','ارتبطت بعض مستحضرات الكركمين عالية التوافر الحيوي بإصابات كبدية.'],url:source.turmeric,query:'curcumin turmeric clinical trials safety liver injury'},
 {id:'fawn',cat:'tcm',name:['Ginkgo Fawn','Ginkgo-Rehkitz','غزال الجنكو'],fact:['Ginkgo biloba has a history in East Asian traditional medicine, but large trials have not shown dementia prevention.','Ginkgo biloba wird traditionell verwendet; große Studien zeigten jedoch keine Demenzprävention.','للجنكو تاريخ في الطب التقليدي بشرق آسيا، لكن التجارب الكبيرة لم تثبت الوقاية من الخرف.'],warn:['Ginkgo can increase bleeding risk with anticoagulants.','Ginkgo kann bei Antikoagulanzien das Blutungsrisiko erhöhen.','قد يزيد الجنكو خطر النزف عند استخدام مضادات التخثر.'],url:source.ginkgo,query:'Ginkgo biloba dementia prevention randomized trial bleeding warfarin'},
 {id:'robin',cat:'tcm',name:['Ginger Robin','Ingwer-Rotkehlchen','أبو الحناء والزنجبيل'],fact:['Ginger (Zingiber officinale; Sheng Jiang when fresh in TCM) has been studied for nausea; evidence varies by clinical context.','Ingwer (Zingiber officinale; frisch als Sheng Jiang in der TCM) wurde gegen Übelkeit untersucht; die Evidenz hängt vom Anwendungsbereich ab.','دُرس الزنجبيل (Sheng Jiang الطازج في الطب الصيني) في حالات الغثيان وتختلف قوة الأدلة بحسب الحالة.'],warn:['Ginger may interact with medicines and can cause gastrointestinal upset.','Ingwer kann Wechselwirkungen und Magen-Darm-Beschwerden verursachen.','قد يتداخل الزنجبيل مع الأدوية ويسبب انزعاجاً هضمياً.'],url:source.ginger,query:'Zingiber officinale ginger nausea systematic review randomized'},
 {id:'firefly',cat:'nutrition',name:['Vitamin Firefly','Vitamin-Glühwürmchen','يراعة الفيتامينات'],fact:['Vitamin and mineral amounts should be compared with reference intakes in the target market; an illustrated label does not verify a dose.','Vitamin- und Mineralstoffmengen müssen mit den Referenzwerten des Zielmarktes abgeglichen werden. Ein Designetikett beweist keine Dosierung.','ينبغي مقارنة كميات الفيتامينات والمعادن بالقيم المرجعية في السوق المستهدفة، ولا يثبت الرسم الموجود على العبوة الجرعة.'],warn:['Child-related product presentation needs age-specific risk assessment.','Bei kinderbezogener Gestaltung ist eine altersgerechte Risikobewertung erforderlich.','تستلزم المنتجات الموجهة للأطفال تقييماً للسلامة حسب العمر.'],url:source.vitamins,query:'vitamin mineral dietary supplements intake reference values review'},
 {id:'dolphin',cat:'nutrition',name:['Hydration Dolphin','Hydratations-Delfin','دلفين الترطيب'],fact:['Fluid needs vary with exercise, temperature and health. Electrolyte drinks are not required for every activity.','Der Flüssigkeitsbedarf variiert je nach Bewegung, Temperatur und Gesundheit. Elektrolytgetränke sind nicht immer nötig.','تختلف الحاجة للسوائل حسب النشاط والحرارة والحالة الصحية، ومشروبات الإلكتروليت ليست ضرورية لكل نشاط.'],warn:['Check sugar, sodium and individual needs before product recommendations.','Vor Empfehlungen Zucker, Natrium und individuellen Bedarf berücksichtigen.','يجب فحص السكر والصوديوم والاحتياجات الفردية قبل التوصية.'],url:'https://www.efsa.europa.eu/en/topics/topic/dietary-reference-values',query:'hydration electrolyte drinks exercise randomized trial systematic review'},
 {id:'eagle',cat:'quality',name:['Safety Eagle','Sicherheits-Adler','نسر السلامة'],fact:['Herbal materials may carry heavy metals, pesticide residues or microbial contamination without adequate quality controls.','Pflanzliche Rohstoffe können ohne Kontrolle Schwermetalle, Pestizidrückstände oder Keime enthalten.','قد تحتوي المواد النباتية على معادن ثقيلة أو بقايا مبيدات أو تلوث ميكروبي دون ضبط جودة ملائم.'],warn:['Evidence and regulatory classification must be evaluated per finished product.','Evidenz und rechtliche Einstufung sind für jedes Fertigprodukt zu prüfen.','يجب تقييم الأدلة والتصنيف التنظيمي لكل منتج نهائي.'],url:source.tcm,query:'herbal medicines contaminants heavy metals pesticides systematic review'},
 {id:'herbal-spirit',cat:'tcm',name:['Panax Ginseng Spirit','Ginseng-Pflanzengeist','روح الجنسنغ'],fact:['Asian ginseng (Panax ginseng; Ren Shen in TCM) contains ginsenosides. Human research on fatigue and cognition remains mixed.','Asiatischer Ginseng (Panax ginseng; Ren Shen) enthält Ginsenoside. Humanstudien zu Müdigkeit und Kognition liefern gemischte Ergebnisse.','يحتوي الجنسنغ الآسيوي (Ren Shen) على الجينسينوسيدات، وتبقى الدراسات البشرية عن التعب والإدراك متباينة.'],warn:['Drug interactions and suitability in pregnancy require medical review.','Wechselwirkungen und Eignung in der Schwangerschaft bedürfen ärztlicher Prüfung.','تتطلب التداخلات الدوائية والملاءمة أثناء الحمل مراجعة طبية.'],url:source.ginseng,query:'Panax ginseng fatigue meta-analysis randomized clinical trial'},
 {id:'alpaca',cat:'nutrition',name:['Balanced Nutrition Alpaca','Ernährungs-Alpaka','ألباكا التغذية المتوازنة'],fact:['Nutrients act in the context of overall dietary intake. More supplementation is not always better, especially for fat-soluble vitamins.','Nährstoffe wirken im Kontext der gesamten Ernährung. Mehr Supplementierung ist nicht automatisch besser, insbesondere bei fettlöslichen Vitaminen.','تعمل المغذيات ضمن النظام الغذائي الكامل، وزيادة المكملات ليست دائماً أفضل خصوصاً للفيتامينات الذائبة في الدهون.'],warn:['Evaluate total exposure from diet, supplements and fortified foods.','Gesamtzufuhr aus Ernährung, Supplementen und angereicherten Lebensmitteln prüfen.','يجب تقييم المدخول الكلي من الطعام والمكملات والأغذية المدعمة.'],url:source.vitamins,query:'multivitamin supplements benefit harms systematic review'},
 {id:'leafbuddy',cat:'quality',name:['Sustainable Leaf Buddy','Nachhaltiges Blättchen','صديق الورقة المستدام'],fact:['Sustainable sourcing requires traceable botanical identity, environmental management and reproducible material specifications.','Nachhaltige Beschaffung benötigt Rückverfolgbarkeit, botanische Identität und reproduzierbare Spezifikationen.','تحتاج المصادر المستدامة إلى التتبع وتحديد الهوية النباتية ومواصفات مواد قابلة للتكرار.'],warn:['A green image or natural origin does not establish sustainability or safety.','Grüne Gestaltung und natürliche Herkunft beweisen weder Nachhaltigkeit noch Sicherheit.','التصميم الأخضر أو الأصل الطبيعي لا يثبت الاستدامة أو السلامة.'],url:source.european,query:'botanical raw material traceability herbal quality standardization'}
];
const associated={owl:['mental-focus'],fox:['cleanox','golden-maca'],rabbit:['probio-gum','prebiotic-fiber'],bee:['herbal-cough-syrup','botanical-infusion'],otter:['omega-3-gum'],robot:['probio-gum'],
 'leaf-spirit':['botanical-infusion','golden-maca'],koala:['cleanox'],chameleon:['oxy-protect','cleanox'],fawn:['mental-focus'],robin:['herbal-cough-syrup','meta-booster'],firefly:['vita-straw','vitamin-d3-k2'],dolphin:['electrolyte-hydration','vita-straw'],eagle:['eye-drops','saline-nasal-drops'],'herbal-spirit':['mental-focus','meta-booster'],alpaca:['power-shake-vegan','protein-essentials'],leafbuddy:['superfood','botanical-infusion']};
const focus={
 'herbal-cough-syrup':['Botanical ingredients: thyme, mallow, elderflower, honey and lemon. Historical concept; cough-treatment claims not established.','Pflanzenprofil: Thymian, Malve, Holunderblüten, Honig und Zitrone. Historisches Konzept ohne geprüfte Husten-Heilaussage.','ملف نباتي: الزعتر والخبيزة وزهرة البيلسان والعسل والليمون. مفهوم تاريخي بلا ادعاء علاجي مؤكد للسعال.','thyme mallow elderflower cough herbal clinical trial'],
 'omega-3-gum':['EPA and DHA lipid nutrition','Ernährung mit EPA und DHA','تغذية أحماض EPA وDHA','omega-3 EPA DHA gum bioavailability'],
 'probio-gum':['Strain-specific oral microbiome research','Stammspezifische Forschung zum oralen Mikrobiom','بحث سلالات ميكروبيوم الفم','Lactobacillus salivarius SGL03 periodontal'],
 'vita-straw':['Vitamins, minerals and formulation review','Vitamine, Mineralstoffe und Rezepturprüfung','الفيتامينات والمعادن ومراجعة التركيبة','multivitamin mineral drink straw nutrient stability'],
 'carbohydrate-blocker':['Botanical formulation and unconfirmed weight-control claims','Pflanzenrezeptur und nicht bestätigte Gewichtsangaben','تركيبة نباتية وادعاءات وزن غير مؤكدة','carbohydrate blocker supplements clinical evidence safety'],
 cleanox:['Artichoke, milk thistle, turmeric, grape seed and dandelion: identity and safety must be checked; “detox” is not established.','Artischocke, Mariendistel, Kurkuma, Traubenkerne und Löwenzahn: Identität und Sicherheit prüfen; „Detox“ ist nicht belegt.','الخرشوف وشوك الحليب والكركم وبذور العنب والهندباء: يلزم التحقق من الهوية والسلامة؛ وادعاء إزالة السموم غير مثبت.','milk thistle silymarin clinical trial'],
 'cranberry-concentrate':['Cranberry constituents and study of urinary-tract outcomes; no product treatment claim.','Cranberry-Inhaltsstoffe und Forschung zu Harnwegsendpunkten; keine produktspezifische Therapieaussage.','مركبات التوت البري والبحث في مخرجات المسالك البولية دون ادعاء علاجي للمنتج.','cranberry urinary tract infections Cochrane review'],
 'golden-maca':['Maca root botanicals and nutritional composition','Maca-Wurzel und Nährstoffzusammensetzung','جذور الماكا والتركيب الغذائي','Lepidium meyenii maca clinical trials review'],
 'mental-focus':['Ginkgo, ginseng, bacopa and B vitamins; cognition claims require verification.','Ginkgo, Ginseng, Bacopa und B-Vitamine; Kognitionsaussagen sind zu prüfen.','الجنكو والجنسنغ والباكوبا وفيتامينات B؛ ادعاءات الإدراك تتطلب التحقق.','ginkgo ginseng bacopa cognition systematic review'],
 'joint-support':['Glucosamine, chondroitin, MSM and plant extracts; allergens and clinical evidence vary.','Glucosamin, Chondroitin, MSM und Pflanzenextrakte; Allergene und Evidenz variieren.','الغلوكوزامين والكوندرويتين وMSM ومستخلصات نباتية؛ تختلف الأدلة والحساسية.','glucosamine chondroitin MSM osteoarthritis systematic review'],
 'oxy-protect':['Grape seed, blueberry, turmeric and selected vitamins; “antioxidant” does not prove clinical outcomes.','Traubenkern, Heidelbeere, Kurkuma und Vitamine; „antioxidativ“ belegt keine klinische Wirkung.','بذور العنب والتوت الأزرق والكركم والفيتامينات؛ مضادات الأكسدة لا تثبت نتائج سريرية.','polyphenols grape seed blueberry human clinical trials'],
 'meta-booster':['Maca, ginseng, ginger and B vitamins; avoid unverified metabolic promises.','Maca, Ginseng, Ingwer und B-Vitamine; unbelegte Stoffwechselversprechen vermeiden.','الماكا والجنسنغ والزنجبيل وفيتامينات B؛ تجنب الادعاءات غير المثبتة عن الأيض.','Panax ginseng maca ginger clinical trial'],
 superfood:['Spirulina, chlorella, berries and seeds; test purity and contaminant risk.','Spirulina, Chlorella, Beeren und Samen; Reinheit und Kontaminationsrisiken prüfen.','السبيرولينا والكلوريلا والتوت والبذور؛ يجب فحص النقاء والتلوث.','spirulina chlorella microalgae supplements safety review'],
 bcaa:['Leucine, isoleucine and valine as branched-chain amino acids.','Leucin, Isoleucin und Valin als verzweigtkettige Aminosäuren.','الليوسين والأيزوليوسين والفالين كأحماض أمينية متفرعة السلسلة.','branched chain amino acids exercise randomized trials'],
 'power-shake-vegan':['Pea, rice and hemp protein sources; evaluate amino acid composition and allergens.','Erbsen-, Reis- und Hanfprotein; Aminosäurenprofil und Allergene prüfen.','بروتين البازلاء والأرز والقنب؛ ينبغي تقييم الأحماض الأمينية والحساسية.','plant protein pea rice hemp protein quality amino acid'],
 'saline-nasal-drops':['Isotonic saline concept; sterilization and classification need verification.','Isotonisches Kochsalzkonzept; Sterilisation und rechtliche Einordnung prüfen.','مفهوم محلول ملحي متساوي التوتر؛ يلزم التحقق من التعقيم والتصنيف.','isotonic saline nasal drops systematic review'],
 'eye-drops':['Hyaluronic acid eye-drop concept; sterility and device/medicine rules apply.','Hyaluronsäure-Augentropfenkonzept; Sterilität und Produktrecht prüfen.','قطرات عين بحمض الهيالورونيك؛ التعقيم وقواعد الأجهزة أو الأدوية مهمة.','hyaluronic acid dry eye drops systematic review'],
 'animal-supplements':['Species-specific formulation, dose and veterinary oversight are essential.','Artenbezogene Rezeptur, Dosierung und veterinärrechtliche Prüfung sind nötig.','التركيبة والجرعة المناسبة للنوع الحيواني والمراجعة البيطرية أساسية.','companion animal supplements veterinary nutrition review'],
 'magnesium-minerals':['Magnesium nutrition, salt-form bioavailability and safe intake.','Magnesium, Bioverfügbarkeit der Salzform und sichere Zufuhr.','تغذية المغنيسيوم والتوافر الحيوي والأمان.','magnesium supplement bioavailability clinical trials'],
 'vitamin-d3-k2':['Vitamin D and K nutrition; determine dose and potential medication interactions.','Vitamin-D- und -K-Versorgung; Dosis und mögliche Wechselwirkungen prüfen.','تغذية فيتاميني D وK؛ تحقق من الجرعة والتداخلات الدوائية.','vitamin D K supplementation trial'],
 'prebiotic-fiber':['Dietary fiber fermentation and gastrointestinal tolerance.','Ballaststofffermentation und gastrointestinale Verträglichkeit.','تخمّر الألياف الغذائية وتحمل الجهاز الهضمي.','prebiotic dietary fiber gastrointestinal randomized trials'],
 'electrolyte-hydration':['Sodium and electrolyte composition should match product use cases.','Natrium und Elektrolyte müssen zum vorgesehenen Einsatz passen.','يجب مواءمة الصوديوم والإلكتروليتات مع الاستعمال المقصود.','electrolyte beverages hydration exercise clinical trials'],
 'botanical-infusion':['Correct botanical identity and food-safety tests matter.','Botanische Identität und Lebensmittelsicherheit sind wichtig.','هوية النبات الصحيحة وفحوص سلامة الغذاء أساسية.','herbal infusions contaminants food safety'],
 'protein-essentials':['Protein quality, amino-acid profile and serving size require formulation work.','Proteinqualität, Aminosäureprofil und Portionsgröße erfordern Rezepturarbeit.','تحتاج جودة البروتين والأحماض الأمينية وحجم الحصة إلى ضبط التركيبة.','protein quality plant supplementation systematic review']
};
const historic={
 'omega-3-gum':{ref:'2018 Innovation Gums – Omega 3 brochure',rows:[['DHA','60 mg','180 mg'],['EPA','55 mg','165 mg'],['EPA + DHA','115 mg','345 mg']],unit:['pergum','per3'],recipe:[
 'Historical brochure lists EPA-rich oil from fish, DHA-rich oil from algae, gum base, sweeteners and soy lecithin; fish and soy allergens require validation.',
 'Historische Broschüre nennt EPA-reiches Fischöl, DHA-reiches Algenöl, Kaumasse, Süßungsmittel und Sojalecithin; Fisch- und Sojaallergene prüfen.',
 'يذكر الكتيب التاريخي زيتاً غنياً بـ EPA من السمك وزيتاً غنياً بـ DHA من الطحالب وقاعدة علكة ومحليات وليسيثين الصويا؛ يلزم فحص مسببات الحساسية.'],warning:[
 'A proposed 3-gum serving is shown in the brochure. Do not infer current dosage, efficacy or authorised claims from that example.',
 'Die Broschüre zeigt drei Kaugummis als Vorschlag. Daraus folgen keine bestätigte aktuelle Verzehrempfehlung oder zugelassene Wirkungsaussagen.',
 'يُظهر الكتيب ثلاث علكات كاقتراح تاريخي؛ لا يعني ذلك جرعة حالية مؤكدة أو ادعاءً صحياً مرخصاً.'],reference:source.omega},
 'probio-gum':{ref:'2018 Innovation Gums – Probio Gum brochure',rows:[['L. salivarius SGL03','30 mg','60 mg'],['Culture count as printed','3 Mld*','6 Mld*'],['Vitamin C','40 mg','80 mg'],['Vitamin E','6 mg','12 mg'],['Vitamin A','Unit unresolved','Unit unresolved']],unit:['pergum','per2'],recipe:[
 'Historical brochure lists L. salivarius SGL03, gum base, sorbitol, isomalt, sweeteners and vitamins C, E and A. “3 Mld” is printed for one gum; viability, expiry count and the meaning of the unit require validation.',
 'Historische Broschüre nennt L. salivarius SGL03, Kaumasse, Sorbitol, Isomalt, Süßungsmittel und Vitamine C, E und A. „3 Mld“ steht pro Kaugummi; Lebendkeimzahl, Haltbarkeit und Einheit müssen geprüft werden.',
 'يذكر الكتيب سلالة L. salivarius SGL03 وقاعدة علكة وسوربيتول وإيزومالت ومحليات وفيتامينات C وE وA. تمت طباعة 3 Mld لكل علكة، لكن حيوية البكتيريا والعدد عند نهاية الصلاحية ووحدة القياس غير موثقة.'],warning:[
 'The brochure appears to print vitamin A in mg; do not use this as a valid label amount. The SGL03 trial was conducted with a suspension, not this gum.',
 'Die Broschüre zeigt Vitamin A offenbar in mg; diese Einheit ist für eine Kennzeichnung ungeprüft. Die SGL03-Studie prüfte eine Suspension, nicht diesen Kaugummi.',
 'يبدو أن وحدة فيتامين A مطبوعة بالميليغرام، فلا يجوز اعتمادها للملصق. درست تجربة SGL03 مستحلباً وليس هذه العلكة.'],reference:source.probio},
 'vita-straw':{ref:'Vita Straw – Deutsch brochure; Vita Straw brochure',rows:[['Vitamin A','120 µg','15% historical NRV'],['Vitamin C','12 mg','15% historical NRV'],['Vitamin D','Not listed','Do not add'],['Vitamin E','1.8 mg','15% historical NRV'],['Vitamin B12','0.375 µg','15% historical NRV'],['Zinc','1.5 mg','15% historical NRV'],['Selenium','8.25 µg','15% historical NRV'],['Biotin / B8','Inconsistent unit','Must verify']],unit:['perstraw','specifics'],recipe:[
 'Strawberry-flavour concept with 15 straws (90 g total) in the German brochure. Ingredients include sucrose, glucose syrup, sorbitol, citric acid, vitamins and mineral salts; the brochure also lists cochineal/carmine. One straw is shown for 200 mL water. This is not sugar-free.',
 'Erdbeer-Konzept mit 15 Trinkhalmen (90 g) laut deutscher Broschüre. Zutaten u. a. Saccharose, Glukosesirup, Sorbitol, Zitronensäure, Vitamine, Mineralsalze und Cochenille/Karmin. Ein Strohhalm wird für 200 ml Wasser gezeigt. Nicht zuckerfrei.',
 'مفهوم بنكهة الفراولة، 15 شفاطة (90 غ) حسب الكتيب الألماني. يحتوي على السكروز وشراب الغلوكوز والسوربيتول وحمض الليمون والفيتامينات والمعادن وصبغة القرمز. تذكر التعليمات شفاطة واحدة مع 200 مل ماء؛ المنتج ليس خالياً من السكر.'],warning:[
 'Biotin is printed inconsistently across supplied material. Cochineal is animal-derived and can trigger sensitivity; age suitability and nutrient data must be checked.',
 'Biotin ist in den vorgelegten Unterlagen uneinheitlich angegeben. Cochenille stammt von Tieren und kann Unverträglichkeiten auslösen; Alterseignung und Nährwerte prüfen.',
 'وحدة البيوتين غير متسقة في الملفات، وصبغة القرمز ذات أصل حيواني وقد تسبب تحسساً؛ يلزم التحقق من العمر المناسب والقيم الغذائية.'],reference:source.vitamins}
};
const cells={
 de:{'Culture count as printed':'Kulturzahl laut Broschüre','Unit unresolved':'Einheit ungeklärt','Not listed':'Nicht aufgeführt','Do not add':'Nicht ergänzen','15% historical NRV':'15 % historischer NRV','Inconsistent unit':'Widersprüchliche Einheit','Must verify':'Prüfung erforderlich'},
 ar:{'Culture count as printed':'عدد المزارع حسب الكتيب','Unit unresolved':'وحدة غير مؤكدة','Not listed':'غير مذكور','Do not add':'لا يُضاف','15% historical NRV':'15٪ من القيمة المرجعية التاريخية','Inconsistent unit':'وحدة غير متسقة','Must verify':'يجب التحقق'}
};
const names={};function lang(){let v=localStorage.getItem('pharmed-language')||document.documentElement.lang||'en';return terms[v]?v:'en'}function t(k){return terms[lang()][k]||terms.en[k]||k}function loc(a){return a[lang()==='de'?1:lang()==='ar'?2:0]}const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\'':'&#39;'}[c]));
function localizedCell(v){return (cells[lang()]||{})[v]||v}
function anchor(url,label){return `<a href="${esc(url)}" target="_blank" rel="noopener noreferrer" class="phs-link">${esc(label)} ↗</a>`}
function selectedImage(){return {
 'omega-3-gum':'assets/redesign/omega-3-gum-science.webp','probio-gum':'assets/redesign/probio-gum-science.webp','vita-straw':'assets/redesign/vita-straw-science.webp'};}
function switchPhotos(){if(typeof PRODUCTS!=='undefined'){PRODUCTS.forEach(p=>{if(selectedImage()[p.id])p.image=selectedImage()[p.id]})}const originals={'assets/omega-3-gum.webp':selectedImage()['omega-3-gum'],'assets/probio-gum.webp':selectedImage()['probio-gum'],'assets/vita-straw.webp':selectedImage()['vita-straw']};document.querySelectorAll('img').forEach(img=>{const src=img.getAttribute('src');if(originals[src])img.setAttribute('src',originals[src]);});}
function linkedProducts(id){if(typeof PRODUCTS==='undefined')return '';const links=(associated[id]||[]).map(key=>PRODUCTS.find(p=>p.id===key)).filter(Boolean);return links.length?`<div class="phs-products-links"><strong>${esc(t('relatedConcepts'))}</strong>${links.map(p=>`<a href="product.html?id=${encodeURIComponent(p.id)}#phs-formula">${esc(p.name)} →</a>`).join('')}</div>`:''}
function subjectCard(s){return `<article class="phs-card" data-category="${s.cat}" id="science-${s.id}"><div class="phs-top"><img src="${asset+s.id}.webp" alt="${esc(loc(s.name))}" loading="lazy"><div><span class="phs-kicker">${esc(t(s.cat))}</span><h3>${esc(loc(s.name))}</h3></div></div><p>${esc(loc(s.fact))}</p><div class="phs-caution"><strong>${esc(t('caution'))}:</strong> ${esc(loc(s.warn))}</div><div class="phs-actions">${anchor(s.url,t('read'))}${anchor(pubmed(s.query),t('pubmed'))}</div>${linkedProducts(s.id)}</article>`}
function productDossier(p){const h=historic[p.id];const a=focus[p.id];const target=a?loc(a):t('concept');const safe=(p.description||{})[lang()]||(p.description||{}).en||'';const food=(h?h.recipe[lang()==='de'?1:lang()==='ar'?2:0]:safe);let rows='';if(h){const [col1,col2]=h.unit.map(k=>t(k));rows=`<div class="phs-table-wrap"><table class="phs-table"><thead><tr><th>${esc(t('ingredient'))}</th><th>${esc(col1)}</th><th>${esc(col2)}</th></tr></thead><tbody>${h.rows.map(r=>`<tr>${r.map(v=>`<td>${esc(localizedCell(v))}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="phs-small">*${esc(h.ref)} · ${esc(t('brochure'))}</p>`}
const fig={'omega-3-gum':'omega-3-pathway.svg','probio-gum':'probio-pathway.svg','vita-straw':'vita-pathway.svg'}[p.id];return `<article class="phs-dossier" id="phs-dossier-${p.id}"><div class="phs-dossier-head"><span class="phs-kicker">${esc(t('dossier'))}</span><h3>${esc(p.name)}</h3><p>${esc(t('sourceinfo'))}</p></div><div class="phs-dossier-grid"><div><h4>${esc(t('recipe'))}</h4><p>${esc(food)}</p><h4>${esc(t('target'))}</h4><p>${esc(target)}</p><div class="phs-caution">${esc(h?loc(h.warning):t('concept'))}</div></div><div><h4>${esc(h?t('specifics'):t('evidence'))}</h4>${rows||`<p>${esc(t('concept'))}</p>`}<div class="phs-actions">${anchor(h?h.reference:source.vitamins,t('read'))}${anchor(pubmed(a?a[3]:p.name+' systematic review'),t('pubmed'))}</div></div>${fig?`<figure class="phs-figure"><img src="assets/science/${fig}" alt="Scientific verification steps for ${esc(p.name)}" loading="lazy"><figcaption>${esc(t('sourceinfo'))}</figcaption></figure>`:''}</div></article>`}
function injectMenu(){let nav=document.querySelector('.links');if(nav&&!nav.querySelector('a[href="science.html"]')){const a=document.createElement('a');a.href='science.html';a.textContent=t('science');if(document.body.dataset.page==='science')a.className='active';nav.append(a)}}
function setPageMeta(){if(document.body.dataset.page==='science')document.title=t('academy')+' | Pharmed UG'}
function insertHome(){const c=document.querySelector('#content');if(!c||c.querySelector('.phs-home'))return;const s=document.createElement('section');s.className='phs-home phs-section';s.innerHTML=`<div class="wrap phs-home-inner"><div><span class="phs-kicker">Pharmed UG · Science. Nature. Well-being.</span><h2>${esc(t('academy'))}</h2><p>${esc(t('intro'))}</p><div class="actions"><a href="science.html" class="btn">${esc(t('home'))} →</a><a href="science.html#phs-products" class="btn outline">${esc(t('three'))}</a></div></div><img src="${asset}owl.webp" loading="lazy" alt="Pharmed scientific owl"></div>`;c.append(s)}
function addMascotButtons(){const cards=document.querySelectorAll('.ph-mascot-card');cards.forEach(card=>{const id=card.querySelector('[data-mascot]')?.getAttribute('data-mascot');if(!id||card.querySelector('.phs-mascot-link'))return;const base=card.querySelector('.ph-mascot-caption');if(!base)return;const a=document.createElement('a');a.className='phs-mascot-link';a.href='science.html?character='+encodeURIComponent(id)+'#science-'+encodeURIComponent(id);a.textContent=t('learn')+' →';base.appendChild(a)})}
function addProductButtons(){document.querySelectorAll('.product-card').forEach(card=>{const link=card.querySelector('a[href^="product.html?id="]');if(!link||card.querySelector('.phs-detail-link'))return;const a=document.createElement('a');a.href=link.getAttribute('href')+'#phs-formula';a.className='phs-detail-link';a.textContent=t('details')+' →';const body=card.querySelector('.card-body');body?.append(a)})}
function insertDetail(){let p=typeof PRODUCTS!=='undefined'?PRODUCTS.find(x=>x.id===new URLSearchParams(location.search).get('id')):null;const main=document.getElementById('content');if(!p||!main)return;const current=main.querySelector('#phs-formula');if(current)current.remove();const sec=document.createElement('section');sec.className='phs-section';sec.id='phs-formula';sec.innerHTML=`<div class="wrap"><h2>${esc(t('dossier'))}</h2>${productDossier(p)}<p class="phs-disclaimer">${esc(t('sourcewarning'))}</p></div>`;const related=main.querySelector('.pale');if(related)main.insertBefore(sec,related);else main.append(sec);if(location.hash==='#phs-formula')requestAnimationFrame(()=>sec.scrollIntoView({block:'start'}))}
function insertWellness(){const main=document.getElementById('content');if(!main||main.querySelector('.phs-wellness'))return;const s=document.createElement('section');s.className='phs-section phs-wellness';s.innerHTML=`<div class="wrap"><h2>${esc(t('science'))}</h2><p>${esc(t('intro'))}</p><div class="phs-mini-grid">${['herbal-spirit','robin','koala'].map(id=>subjectCard(subjects.find(s=>s.id===id))).join('')}</div><div class="actions"><a class="btn" href="science.html">${esc(t('academy'))} →</a></div></div>`;main.append(s)}
function renderAcademy(){const main=document.getElementById('content');if(!main)return;setPageMeta();const filters=['all','nutrition','herbal','tcm','quality','research'];main.innerHTML=`<section class="phs-header"><div class="wrap"><span class="phs-kicker">Pharmed UG · Science. Nature. Well-being.</span><h1>${esc(t('academy'))}</h1><p class="lead">${esc(t('intro'))}</p><div class="phs-steps" aria-label="Research evidence hierarchy"><span>${esc(t('evidence'))}</span><b>Laboratory</b><i>→</i><b>Human trial</b><i>→</i><b>Systematic review</b><i>→</i><b>Product-specific verification</b></div></div></section><section class="phs-section"><div class="wrap"><div class="phs-section-title"><h2>${esc(t('characters'))}</h2><a href="mascots.html" class="phs-link">${esc(t('gallery'))} →</a></div><input type="search" class="phs-search" placeholder="${esc(t('search'))}" aria-label="${esc(t('search'))}" id="phs-search"><div class="phs-filterbar" role="group" aria-label="Field">${filters.map((k,i)=>`<button data-phs-filter="${k}" class="${i===0?'active':''}">${esc(t(k))}</button>`).join('')}</div><div class="phs-grid" id="phs-grid">${subjects.map(subjectCard).join('')}</div><p class="phs-disclaimer">${esc(t('sourceNote'))}</p></div></section><section class="phs-section phs-integrative-section"><div class="wrap"><h2>${esc(t('integrativeTitle'))}</h2><div class="phs-concepts"><article><span>01</span><h3>${esc(t('complementaryLabel'))}</h3><p>${esc(t('complementaryNote'))}</p></article><article><span>02</span><h3>${esc(t('alternativeLabel'))}</h3><p>${esc(t('alternativeNote'))}</p></article><article><span>03</span><h3>${esc(t('integrativeLabel'))}</h3><p>${esc(t('integrativeNote'))}</p></article></div><div class="phs-actions">${anchor(source.integrative,t('read'))}${anchor(pubmed('complementary alternative integrative medicine evidence systematic review'),t('pubmed'))}</div></div></section><section class="phs-section phs-products-section" id="phs-products"><div class="wrap"><h2>${esc(t('dossier'))}</h2><p>${esc(t('sourcewarning'))}</p><div class="phs-product-list">${(typeof PRODUCTS!=='undefined'?PRODUCTS:[]).map(productDossier).join('')}</div></div></section><section class="phs-section phs-final"><div class="wrap"><h2>${esc(t('claims'))}</h2><p>${esc(t('sourceinfo'))}</p><div class="phs-actions">${anchor(source.eu,'EU health claim rules')}${anchor(source.tcm,'NCCIH: Traditional Chinese Medicine')}${anchor(source.herbs,'NCCIH: Herb–drug interactions')}</div></div></section>`;
const q=document.querySelector('#phs-search');const items=[...document.querySelectorAll('#phs-grid .phs-card')];let filter='all';function draw(){let text=q.value.trim().toLowerCase();items.forEach((item,i)=>{item.hidden=(filter!=='all'&&subjects[i].cat!==filter)||(text&&!item.innerText.toLowerCase().includes(text))})}q.oninput=draw;document.querySelectorAll('[data-phs-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.phsFilter;document.querySelectorAll('[data-phs-filter]').forEach(a=>a.classList.toggle('active',a===b));draw()});
const character=new URLSearchParams(location.search).get('character');if(character){const target=main.querySelector('#science-'+character);if(target){target.classList.add('phs-featured');target.scrollIntoView({block:'center',behavior:'instant'})}}
}
function changePhotos(){switchPhotos()}
function run(){changePhotos();injectMenu();switch(document.body.dataset.page){case 'index':insertHome();break;case 'mascots':addMascotButtons();break;case 'science':renderAcademy();break;case 'wellness':insertWellness();break;case 'products':addProductButtons();break;case 'product':insertDetail();break;}addProductButtons()}
let queued=false;const schedule=()=>{if(queued)return;queued=true;queueMicrotask(()=>{queued=false;run()})};
document.addEventListener('click',e=>{if(e.target.closest('[data-lang]'))schedule()});
const target=document.getElementById('content');if(target){const observer=new MutationObserver(()=>{if(document.body.dataset.page==='mascots'){addMascotButtons()}else if(document.body.dataset.page==='products'){addProductButtons();switchPhotos()}});observer.observe(target,{childList:true,subtree:true})}
run();
window.PHARMED_SCIENCE={sources:source,subjects:subjects,documented:historic};
})();
